-- Behebe Search Path für get_country_vat_rate Funktion
DROP FUNCTION IF EXISTS public.get_country_vat_rate(VARCHAR);

CREATE OR REPLACE FUNCTION public.get_country_vat_rate(p_country VARCHAR(2))
RETURNS DECIMAL(5,2)
LANGUAGE plpgsql
IMMUTABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  CASE p_country
    WHEN 'DE' THEN RETURN 19.00;
    WHEN 'ES' THEN RETURN 21.00;
    WHEN 'AT' THEN RETURN 20.00;
    WHEN 'FR' THEN RETURN 20.00;
    WHEN 'IT' THEN RETURN 22.00;
    WHEN 'NL' THEN RETURN 21.00;
    WHEN 'BE' THEN RETURN 21.00;
    WHEN 'PL' THEN RETURN 23.00;
    WHEN 'PT' THEN RETURN 23.00;
    WHEN 'SE' THEN RETURN 25.00;
    WHEN 'DK' THEN RETURN 25.00;
    WHEN 'FI' THEN RETURN 24.00;
    WHEN 'IE' THEN RETURN 23.00;
    WHEN 'LU' THEN RETURN 17.00;
    WHEN 'GR' THEN RETURN 24.00;
    WHEN 'CZ' THEN RETURN 21.00;
    WHEN 'HU' THEN RETURN 27.00;
    WHEN 'RO' THEN RETURN 19.00;
    WHEN 'BG' THEN RETURN 20.00;
    WHEN 'HR' THEN RETURN 25.00;
    WHEN 'SI' THEN RETURN 22.00;
    WHEN 'SK' THEN RETURN 20.00;
    WHEN 'EE' THEN RETURN 20.00;
    WHEN 'LV' THEN RETURN 21.00;
    WHEN 'LT' THEN RETURN 21.00;
    WHEN 'CY' THEN RETURN 19.00;
    WHEN 'MT' THEN RETURN 18.00;
    ELSE RETURN 0.00;
  END CASE;
END;
$$;